CREATE TABLE public.red_number_processes(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	process_id text unique not null,
	"status" text,
	category text,
	description_title text,
	description_text text
);

CREATE TABLE public.red_number_reports(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_name text unique not null,
    doc_ref text,
    doc_size integer,
    red_number_process_id integer REFERENCES public.red_number_processes(id) ON DELETE CASCADE
);

CREATE TABLE public.parsed_red_number_reports(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "checksum" text,
    "meta" jsonb,
    red_number_report_id integer REFERENCES public.red_number_reports(id) ON DELETE CASCADE
);

CREATE TABLE public.parsed_red_number_report_sections(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	content text,
	token_count integer,
	embedding vector(1536),
	heading text,
    "page" integer,
    parsed_red_number_report_id integer REFERENCES public.parsed_red_number_reports(id) ON DELETE CASCADE
);