CREATE TABLE public.export(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	aktualisiert timestamp
);

CREATE TABLE public.vorgang(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	VNr text,
	VFunktion text,
	ReihNr text,
	VTyp text,
	VTypL text,
	VSys text,
	VSysL text,
	VIR text,
	export_id integer REFERENCES public.export(id)
);

CREATE TABLE public.nebeneintrag(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ReihNr text,
	Desk text,
	vorgang_id integer REFERENCES public.vorgang(id)
);

CREATE TABLE public.dokument(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ReihNr text,
	DHerk text,
	DHerkL text,
	Wp text,
	DokArt text,
	DokArtL text,
	DokTyp text,
	DokTypL text,
	NrInTyp text,
	Desk text,
	Titel text,
	DokNr text,
	DokDat date,
	LokURL text,
	Sb text,
	VkDat date,
	HNr text,
	Jg text,
	-- Abstract field type set to Text due to its potential length variability.
	-- Urheber field type set to Text based on assumption it can contain variety of input lengths.
	Abstract text,
	Urheber text,
	vorgang_id integer REFERENCES public.vorgang(id)
);