CREATE TABLE "public"."parsed_document_tables" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"parsed_document_id" bigint,
	"name" text,
	"accuracy" float,
	"whitespace" float,
	"order" int,
	"page" int
);

CREATE UNIQUE INDEX parsed_document_tables_pkey ON public.parsed_document_tables USING btree(id);

ALTER TABLE "public"."parsed_document_tables"
	ADD CONSTRAINT "parsed_document_tables_pkey" PRIMARY KEY USING INDEX "parsed_document_tables_pkey";

ALTER TABLE "public"."parsed_document_tables"
	ADD CONSTRAINT "parsed_document_tables_parsed_document_id_fkey" FOREIGN KEY (parsed_document_id) REFERENCES parsed_documents(id) NOT valid;

ALTER TABLE "public"."parsed_document_tables" validate CONSTRAINT "parsed_document_tables_parsed_document_id_fkey";