CREATE TABLE "public"."parsed_documents"(
	"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"filename" text,
	"checksum" text,
	"meta" jsonb,
	"dokument_id" bigint
);

CREATE TABLE "public"."parsed_document_sections"(
	"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"parsed_document_id" bigint,
	"content" text,
	"token_count" integer,
	"embedding" vector(1536),
	"heading" text
);

CREATE UNIQUE INDEX parsed_document_sections_pkey ON public.parsed_document_sections USING btree(id);

CREATE UNIQUE INDEX parsed_documents_pkey ON public.parsed_documents USING btree(id);

ALTER TABLE "public"."parsed_document_sections"
	ADD CONSTRAINT "parsed_document_sections_pkey" PRIMARY KEY USING INDEX "parsed_document_sections_pkey";

ALTER TABLE "public"."parsed_documents"
	ADD CONSTRAINT "parsed_documents_pkey" PRIMARY KEY USING INDEX "parsed_documents_pkey";

ALTER TABLE "public"."parsed_document_sections"
	ADD CONSTRAINT "parsed_document_sections_parsed_document_id_fkey" FOREIGN KEY (parsed_document_id) REFERENCES parsed_documents(id) NOT valid;

ALTER TABLE "public"."parsed_document_sections" validate CONSTRAINT "parsed_document_sections_parsed_document_id_fkey";

ALTER TABLE "public"."parsed_documents"
	ADD CONSTRAINT "parsed_documents_dokument_id_fkey" FOREIGN KEY (dokument_id) REFERENCES dokument(id) NOT valid;

ALTER TABLE "public"."parsed_documents" validate CONSTRAINT "parsed_documents_dokument_id_fkey";

