CREATE TABLE public.red_number_reports(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"status" text,
	category text,
	title text,
	text_content text,
    doc_name text,
    doc_ref text
);

CREATE TABLE public.red_number_report_sections(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	content text,
	token_count integer,
	embedding vector(1536),
	heading text
    red_number_report_id integer REFERENCES public.red_number_reports(id)
);