CREATE TABLE public.red_number_processes(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	process_id text,
	"status" text,
	category text,
	description_title text,
	description_text text,
);

CREATE TABLE public.red_number_reports(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_name text,
    doc_ref text,
    doc_size integer,
    red_number_process_id integer REFERENCES public.red_number_processes(id)
);

CREATE TABLE public.red_number_report_sections(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	content text,
	token_count integer,
	embedding vector(1536),
	heading text
    red_number_report_id integer REFERENCES public.red_number_reports(id)
);